### ISSUE TITLE
Vague error (Code 0) calling MASPlugin.start() method

### ISSUE THREAD

**Issue by ErikAugust** [CAAPIM/Cordova-MAS-Foundation#55]
After successfully calling initialize and grantFlow (password), I am calling the start() method and receiving the following error:

`errorInfo: {}, errorMessage: "The operation couldn’t be completed. ( error 0.)", errorCode: 0}
`
This also happens with the alternate start methods - startWithJSON, etc.

The msso_config.json is in the Resources folder inside the Xcode project.

Platform: iOS
Repo: Master

**Comment by ysd24** [comment]
Hi Erik,

Thank you for sharing the issue.
This issue comes if the plugin is unable to read the msso_config.json properly.

Could you share your msso_config.json, if that is permitted, so that we can scrutinise and come to a conclusion.

Thanks,
Syed Yusuf

**Comment by ErikAugust** [comment]
Hi Syed, thanks for help! Do you have an email I may be able to send over the JSON file?

**Comment by manutripathi** [comment]
Hi Eric,
           You can attach the JSON file in this thread itself (if data security is not an issue). May I also know which version of CA API Gateway you have installed and the MAG backend server's version.

**Comment by ErikAugust** [comment]
I'm going to consult with management to remove any properties from the JSON and attach to the thread.

Another question:

Would this error occur if it could not find the file? The file is in the Resources directory of the Xcode project.

**Comment by ErikAugust** [comment]
Quick update: I've changed the port which we knew was incorrect - and reset locally, and now I get a more verbose error:

`{errorInfo: {NSLocalizedDescription: "Invalid endpoint"}, errorMessage: "Invalid endpoint", errorCode: 100204}`

**It appears our "prefix" is not set in the config - could that be the problem?**

Thanks again!

**Comment by manutripathi** [comment]
May be, I cannot be sure without looking into the config file. While sending dont remove any content from the file. Better if can you send it to my email trima09@ca.com and yussy01@ca.com
